/**
 * Standard error codes shared across loa-finn and arrakis.
 */

export const ERROR_CODES = {
  // Auth errors (401/403)
  JWT_INVALID: 'JWT_INVALID',
  JWT_EXPIRED: 'JWT_EXPIRED',
  JTI_REQUIRED: 'JTI_REQUIRED',
  JTI_REPLAY: 'JTI_REPLAY',
  ISSUER_NOT_ALLOWED: 'ISSUER_NOT_ALLOWED',
  AUDIENCE_MISMATCH: 'AUDIENCE_MISMATCH',
  REQ_HASH_MISMATCH: 'REQ_HASH_MISMATCH',
  TIER_INSUFFICIENT: 'TIER_INSUFFICIENT',
  JWKS_UNAVAILABLE: 'JWKS_UNAVAILABLE',

  // Budget errors (402/429)
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  BUDGET_OVERFLOW: 'BUDGET_OVERFLOW',
  RATE_LIMITED: 'RATE_LIMITED',

  // Request errors (400)
  CONTRACT_VERSION_MISMATCH: 'CONTRACT_VERSION_MISMATCH',
  POOL_UNKNOWN: 'POOL_UNKNOWN',
  BODY_TOO_LARGE: 'BODY_TOO_LARGE',
  ENCODING_UNSUPPORTED: 'ENCODING_UNSUPPORTED',
  DECOMPRESSION_BOMB: 'DECOMPRESSION_BOMB',

  // Provider errors (502/503)
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',

  // Runtime errors (500)
  NATIVE_RUNTIME_SPAWN_FAILED: 'NATIVE_RUNTIME_SPAWN_FAILED',
  NATIVE_RUNTIME_TIMEOUT: 'NATIVE_RUNTIME_TIMEOUT',
  NATIVE_RUNTIME_ORPHAN: 'NATIVE_RUNTIME_ORPHAN',
  ENSEMBLE_ALL_FAILED: 'ENSEMBLE_ALL_FAILED',

  // BYOK errors
  BYOK_SESSION_EXPIRED: 'BYOK_SESSION_EXPIRED',
  BYOK_BOUNDED_USE_EXCEEDED: 'BYOK_BOUNDED_USE_EXCEEDED',
  BYOK_NONCE_REPLAY: 'BYOK_NONCE_REPLAY',

  // Reconciliation
  RECONCILIATION_DRIFT: 'RECONCILIATION_DRIFT',
  RECONCILIATION_FAIL_CLOSED: 'RECONCILIATION_FAIL_CLOSED',

  // SSE
  SSE_PARSE_ERROR: 'SSE_PARSE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
