/**
 * `check:dist-parity` — assert the committed `dist/` tree matches the
 * `tsc` output of the current `src/` tree.
 *
 * This is the gate that turns the committed-`dist/` convention from
 * "trust the author ran `npm run build`" into "CI rejects PRs where
 * `dist/` drifts from `src/`". Without this gate, a contributor can
 * edit one and forget the other; with it, the diff a reviewer sees
 * is guaranteed to be the JavaScript that ships.
 *
 * Mechanism:
 *   1. Run `tsc` (writes to `dist/`).
 *   2. Run `git status --porcelain -- dist/` — the unified status
 *      check covers staged, unstaged, AND untracked changes against
 *      HEAD, regardless of index state. A pre-commit hook that
 *      `git add`s dist/ no longer hides drift behind a clean
 *      `git diff` (iter-3 F1 mitigation: index state is developer-
 *      local and unreliable as a CI invariant; HEAD is the ground
 *      truth for build-artifact verification per the Buck2 / Bazel
 *      hermeticity pattern).
 *
 * **State-mutation note** (iter-3 F-002): the script writes to
 * tracked `dist/` files as part of step 1. On failure the working
 * tree is left dirty so the reviewer can inspect the diff; on
 * success the tree is byte-identical to its pre-run state. Running
 * outside CI in a dirty repo is fine — re-run `npm run build` at any
 * point to restore parity. A future variant could build into a temp
 * directory to keep verification non-mutating, at the cost of
 * losing the in-place diff for triage.
 *
 * Wired into `check:all` per the cycle-005 PR-A3.7 iter-2 bridge
 * disposition of F5 (dist/ committed without enforced parity gate).
 *
 * @see CONTRIBUTING.md — "Build artifacts (dist/) policy"
 */
import { execSync } from 'node:child_process';

function run(cmd: string): { code: number; stdout: string; stderr: string } {
  try {
    const stdout = execSync(cmd, { stdio: ['ignore', 'pipe', 'pipe'] }).toString();
    return { code: 0, stdout, stderr: '' };
  } catch (e) {
    const err = e as { status?: number; stdout?: Buffer; stderr?: Buffer };
    return {
      code: err.status ?? 1,
      stdout: err.stdout?.toString() ?? '',
      stderr: err.stderr?.toString() ?? '',
    };
  }
}

// iter-4 F2 mitigation: invoke the same `npm run build` contributors
// run, not `npx tsc` directly. If `npm run build` ever expands beyond
// `tsc` (asset copies, post-processing, schema generation), the gate
// expands with it — single source of truth for "what does building
// this package produce." Doc and CI agree by construction.
console.log('[check:dist-parity] Running `npm run build` (writes dist/)...');
const build = run('npm run build');
if (build.code !== 0) {
  console.error('[check:dist-parity] build failed:');
  console.error(build.stdout);
  console.error(build.stderr);
  process.exit(build.code);
}

// PR-A3.11 (FR-D1) iter-3: invoke the stub's bundle script so the
// parity gate covers both main and stub trees in lockstep. The stub
// is no longer compiled by tsc — its dist/ is generated by
// `node tools/hounfour-stub/scripts/build.mjs` which (a) copies
// main's compiled `dist/` into `tools/hounfour-stub/dist/_main/`
// and (b) writes the stub's `dist/index.js` + `dist/index.d.ts`
// from a deterministic export list. Consumers using `file:./` see
// a self-contained package — relative imports resolve within the
// stub's package boundary so npm's copy-on-install behavior does
// not break the import graph (iter-2 BLOCKER mitigation).
console.log('[check:dist-parity] Bundling hounfour-stub (writes tools/hounfour-stub/dist/)...');
const stubBuild = run('node tools/hounfour-stub/scripts/build.mjs');
if (stubBuild.code !== 0) {
  console.error('[check:dist-parity] stub bundle failed:');
  console.error(stubBuild.stdout);
  console.error(stubBuild.stderr);
  process.exit(stubBuild.code);
}

// iter-3 F1 mitigation: compare against HEAD, not the index.
//   - `git status --porcelain -- <paths>` yields one line per file
//     with status differing from HEAD across staged/unstaged/
//     untracked buckets — a unified check.
//   - A pre-commit hook running `git add dist/` would otherwise hide
//     drift from `git diff`; `git status --porcelain` catches it.
// Both main `dist/` and stub `tools/hounfour-stub/dist/` are scoped
// in the same status check so a single command surfaces drift in
// either tree.
console.log('[check:dist-parity] Comparing committed dist/ (HEAD) against tsc output (main + stub)...');
const status = run('git status --porcelain -- dist/ tools/hounfour-stub/dist/');
if (status.stdout.trim().length > 0) {
  console.error(
    '[check:dist-parity] FAIL: committed dist/ does not match build output.\n' +
      'Either run `npm run build` and `node tools/hounfour-stub/scripts/build.mjs` and commit the result, or check that ' +
      '`src/` (main) or the stub bundle script was edited without rebuilding.\n\n' +
      'Drift summary (one line per file; index-aware):',
  );
  console.error(status.stdout);
  // For triage: also surface the working-tree-vs-HEAD diff so the
  // reviewer can read the actual byte changes, not just file names.
  const headDiff = run('git diff HEAD -- dist/ tools/hounfour-stub/dist/');
  if (headDiff.stdout.length > 0) {
    console.error('\nDetailed diff against HEAD:');
    console.error(headDiff.stdout);
  }
  process.exit(1);
}
console.log('[check:dist-parity] OK: main + stub dist/ trees at HEAD are byte-identical to tsc output.');
