/**
 * `check:crossfield-coverage` — generated cross-field validator coverage
 * (issues #127, #129, #133, #144, #157).
 *
 * Derives coverage from the two real inventories instead of hand-maintained
 * lists:
 *   - schemas/*.json roots carrying `x-cross-field-validated: true`
 *     (the wire-visible marker consumers discover), and
 *   - the runtime registry (`getCrossFieldValidatorSchemas()` from dist/).
 *
 * Enforced invariants:
 *   1. FORWARD (strict): every marked schema has a registered validator.
 *      A marker without a validator advertises validation that never runs.
 *   2. REVERSE (ratchet): registered validators whose generated schema lacks
 *      the marker are reported and counted; the count must not GROW past the
 *      checked-in baseline. Shrinking it is encouraged — update the baseline
 *      downward in the same commit.
 *
 * Also writes docs/architecture/validator-coverage.md (generated report) so
 * release evidence includes the coverage diff; regenerate with
 * `pnpm run check:crossfield-coverage -- --write`.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Reverse-gap baseline: registered validators without a wire-visible marker.
// Ratchet only — lower it as markers are added; the check fails if it grows.
const REVERSE_GAP_BASELINE = 106;

const root = process.cwd();
const writeReport = process.argv.includes('--write');

/**
 * Deterministic PascalCase → kebab-case conversion (`MicroUSDC` →
 * `micro-usdc`, `DisputeRecord` → `dispute-record`). Registry keys are
 * PascalCase TypeBox ids; generated schema slugs are kebab-case. This is
 * the ONE reviewed convention bridging them — unlike the previous
 * strip-all-punctuation normalization, casing/punctuation drift (e.g. a
 * slug `disputerecord`) no longer silently compares equal: it surfaces as
 * marked-but-unregistered and fails the forward gate.
 */
function pascalToKebab(name: string): string {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

function schemaSlug(id: string | undefined, filename: string): string {
  if (id) {
    const tail = id.split('/').pop();
    if (tail) return tail;
  }
  return filename.replace(/\.schema\.json$/, '');
}

async function main(): Promise<void> {
  const schemasDir = resolve(root, 'schemas');
  const marked = new Map<string, string>(); // kebab slug -> display slug (exact)
  for (const file of readdirSync(schemasDir)) {
    if (!file.endsWith('.json')) continue;
    const doc = JSON.parse(readFileSync(resolve(schemasDir, file), 'utf8')) as Record<string, unknown>;
    if (doc['x-cross-field-validated'] === true) {
      const slug = schemaSlug(doc.$id as string | undefined, file);
      marked.set(slug, slug);
    }
  }

  const validators = await import(resolve(root, 'dist/validators/index.js')) as {
    getCrossFieldValidatorSchemas(): string[];
  };
  const registered = new Map<string, string>(); // kebab(key) -> registry key
  for (const key of validators.getCrossFieldValidatorSchemas()) {
    const kebab = pascalToKebab(key);
    if (registered.has(kebab)) {
      // Two PascalCase keys collapsing to one kebab slug would make the
      // coverage comparison ambiguous — surface instead of guessing.
      console.error(
        `[check:crossfield-coverage] FAIL: registry keys '${registered.get(kebab)}' and ` +
          `'${key}' both map to kebab slug '${kebab}'.`,
      );
      process.exit(1);
    }
    registered.set(kebab, key);
  }

  const markedUnregistered = [...marked.entries()]
    .filter(([n]) => !registered.has(n))
    .map(([, slug]) => slug)
    .sort();
  const registeredUnmarked = [...registered.entries()]
    .filter(([n]) => !marked.has(n))
    .map(([, key]) => key)
    .sort();

  const lines = [
    '# Cross-Field Validator Coverage (generated)',
    '',
    `> Generated by \`scripts/check-crossfield-coverage.ts\` — do not edit by hand.`,
    `> Regenerate: \`pnpm run check:crossfield-coverage -- --write\``,
    '',
    `| Inventory | Count |`,
    `|-----------|-------|`,
    `| Schemas marked \`x-cross-field-validated\` | ${marked.size} |`,
    `| Registered cross-field validators | ${registered.size} |`,
    `| Marked but UNREGISTERED (must be 0) | ${markedUnregistered.length} |`,
    `| Registered but unmarked (ratchet ≤ ${REVERSE_GAP_BASELINE}) | ${registeredUnmarked.length} |`,
    '',
    '## Registered but unmarked',
    '',
    'These validators run at runtime but the generated JSON Schema does not',
    'advertise `x-cross-field-validated` to cross-language consumers. Add the',
    'marker to the TypeBox schema options when touching these schemas, then',
    'lower the ratchet baseline.',
    '',
    ...registeredUnmarked.map((k) => `- ${k}`),
    '',
  ];

  if (writeReport) {
    writeFileSync(resolve(root, 'docs/architecture/validator-coverage.md'), lines.join('\n'));
    console.log('[check:crossfield-coverage] wrote docs/architecture/validator-coverage.md');
  }

  let failed = false;
  if (markedUnregistered.length > 0) {
    console.error(
      `[check:crossfield-coverage] FAIL: ${markedUnregistered.length} schema(s) marked ` +
        `x-cross-field-validated have NO registered validator:\n  ${markedUnregistered.join('\n  ')}`,
    );
    failed = true;
  }
  if (registeredUnmarked.length > REVERSE_GAP_BASELINE) {
    console.error(
      `[check:crossfield-coverage] FAIL: registered-but-unmarked gap grew to ` +
        `${registeredUnmarked.length} (baseline ${REVERSE_GAP_BASELINE}). New cross-field ` +
        `validators MUST set 'x-cross-field-validated': true on their schema.`,
    );
    failed = true;
  }
  if (registeredUnmarked.length < REVERSE_GAP_BASELINE) {
    // Improvements MUST ratchet: a warn-and-pass here would leave a stale
    // higher baseline that lets a later PR reintroduce unmarked validators
    // up to the old count without failing CI.
    console.error(
      `[check:crossfield-coverage] FAIL: reverse gap improved to ${registeredUnmarked.length}, ` +
        `below the baseline ${REVERSE_GAP_BASELINE}. Lower REVERSE_GAP_BASELINE to ` +
        `${registeredUnmarked.length} in this commit so the improvement sticks.`,
    );
    failed = true;
  }

  if (failed) process.exit(1);
  console.log(
    `[check:crossfield-coverage] OK: ${marked.size} marked schemas all registered; ` +
      `reverse gap ${registeredUnmarked.length}/${REVERSE_GAP_BASELINE}.`,
  );
}

main().catch((err) => {
  console.error('[check:crossfield-coverage] ERROR:', err);
  process.exit(1);
});
