/**
 * Generate RELEASE-INTEGRITY.json — SHA-256 checksums for all published artifacts.
 * Consumers can verify downloaded schemas, vectors, and constraints against this manifest.
 *
 * Usage: npx tsx scripts/generate-release-integrity.ts
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isVectorExcluded as isVectorExcludedAbs } from './lib/release-integrity-predicates.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));

function sha256(filePath: string): string {
  const content = readFileSync(filePath);
  return createHash('sha256').update(content).digest('hex');
}

function walkDir(dir: string, ext: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(fullPath, ext));
    } else if (entry.isFile() && entry.name.endsWith(ext)) {
      results.push(fullPath);
    }
  }
  return results.sort();
}

interface FileChecksum {
  path: string;
  sha256: string;
  size_bytes: number;
}

// `schemas` filters to `.schema.json` so the integrity totals match the count
// reported in `schemas/README.md` (generated by `schema:generate`). The two
// auto-generated manifest files in `schemas/` (`index.json`,
// `schemastore-catalog.json`) are tracked under the separate `manifests`
// category — they remain checksummed for tamper detection but are not
// counted against the schemas total.
//
// PR-A3.12 iter-2 mitigation (integrity_file_incomplete): the `vectors`
// category previously walked only `vectors/conformance/` (legacy
// pre-v8.4.0 multi-vector files). The cycle-005 cluster's per-file
// fixture layout (`vectors/<Schema>/v8.6.0/{valid,invalid,boundary,
// invalid-cross-field}/*.json`) was uncounted — totals.vectors=233
// while the actual fixture corpus carries ≥1,200 files. The manifest
// now walks the entire `vectors/` tree and applies a vectors-scoped
// exclusion filter for non-fixture files (trace diagnostics, tooling
// registries). PR-A3.12 iter-3 fix (23d6a2a0 + F-001): the exclusion
// predicate is now per-category (only the `vectors` category gets the
// filter; schemas/constraints walk unfiltered) and the `_meta/`
// branch returns true (excluded) per the documented intent — iter-2
// shipped an inverted predicate that included _meta/ files.
// PR-A3.12 iter-4 mitigation (F-001 + path-bug-1): exclusion checks
// operate on a forward-slash-normalized path *relative to the repo root*.
// The predicate itself lives in `./lib/release-integrity-predicates.ts`
// (extracted in PR-B1.0 hygiene so the truth table can be pinned by
// unit tests — `tests/scripts/release-integrity-predicates.test.ts`).
// Bound here with the resolved `root` so the call sites stay one-arg.
const isVectorExcluded = (absPath: string): boolean =>
  isVectorExcludedAbs(absPath, root);

const dirs = [
  { dir: join(root, 'schemas'), ext: '.schema.json', category: 'schemas',
    exclude: undefined as ((p: string) => boolean) | undefined },
  { dir: join(root, 'vectors'), ext: '.json', category: 'vectors',
    exclude: isVectorExcluded },
  { dir: join(root, 'constraints'), ext: '.json', category: 'constraints',
    exclude: undefined as ((p: string) => boolean) | undefined },
] as const;

const explicitManifestPaths = [
  join(root, 'schemas', 'index.json'),
  join(root, 'schemas', 'schemastore-catalog.json'),
] as const;

// PR-A3.12 iter-5 mitigation (F-001 finer-grain rotation): emitted `path`
// fields are POSIX-normalized so manifest bytes are platform-independent.
// On Linux/macOS this is a no-op (`relative()` already emits `/`); the
// normalization is purely defensive against a future Windows
// contributor checkout serializing backslashes into the manifest and
// silently breaking byte-equality reproducibility.
const toPosixRel = (absPath: string): string =>
  relative(root, absPath).split(sep).join('/');

const checksums: Record<string, FileChecksum[]> = {};
const totals: Record<string, number> = {};
let totalFiles = 0;

for (const { dir, ext, category, exclude } of dirs) {
  const allFiles = walkDir(dir, ext);
  const files = exclude ? allFiles.filter((f) => !exclude(f)) : allFiles;
  checksums[category] = files.map((f) => ({
    path: toPosixRel(f),
    sha256: sha256(f),
    size_bytes: statSync(f).size,
  }));
  totals[category] = checksums[category].length;
  totalFiles += checksums[category].length;
}

const manifestFiles = explicitManifestPaths
  .filter((p) => {
    try {
      statSync(p);
      return true;
    } catch {
      return false;
    }
  })
  .sort();
checksums.manifests = manifestFiles.map((f) => ({
  path: toPosixRel(f),
  sha256: sha256(f),
  size_bytes: statSync(f).size,
}));
totals.manifests = checksums.manifests.length;
totalFiles += checksums.manifests.length;

const manifest = {
  release_version: pkg.version,
  generated_at: new Date().toISOString(),
  generator: 'generate-release-integrity.ts',
  totals: {
    ...totals,
    total: totalFiles,
  },
  verification: 'sha256sum <file> | grep $(jq -r \'.checksums.<category>[] | select(.path=="<file>") | .sha256\' RELEASE-INTEGRITY.json)',
  checksums,
};

const outPath = join(root, 'RELEASE-INTEGRITY.json');
writeFileSync(outPath, JSON.stringify(manifest, null, 2) + '\n');

console.log(`RELEASE-INTEGRITY.json generated:`);
console.log(`  version:     ${manifest.release_version}`);
console.log(`  schemas:     ${totals.schemas}`);
console.log(`  manifests:   ${totals.manifests}`);
console.log(`  vectors:     ${totals.vectors}`);
console.log(`  constraints: ${totals.constraints}`);
console.log(`  total:       ${totalFiles} files`);
